targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/people/model/**.dart

# based on https://codewithandrea.com/tips/speed-up-code-generation-build-runner-dart-flutter/